# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
commands:
  print_pipeline_id:
    steps:
      - run: echo ${CIRCLE_WORKFLOW_ID}

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  save-say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo 'Hello, World!' > ~/output.txt"
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt
  print-machine-info:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "print-machine-info"
          command: "echo Hello, World!;uname -a"
      - run:
          name: "What branch am I on now?"
          command: "echo $CIRCLE_BRANCH"
      - attach_workspace:
          at: ~/         
      - run:
          name: "What is global variable now?"
          command: "ls -lh ~/"
      - run: cat ~/output.txt 
      - print_pipeline_ids
      - run: echo "test on fail"
            when: on_fail       
workflows:
  say-hello-workflow:
    jobs:
      - save-say-hello
      - print-machine-info:
          requires:
            - save-say-hello